#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Uzycie: $0 <nazwa_uzytkownika>"
    exit 1
fi

for arg in "$@"; do
    username=$arg
	if id "$username" &>/dev/null; then
	    echo "Uzytkownik $username juz istnieje. Prosze podac inna nazwę uzytkownika."
	    continue
	fi

	if [ "$(id -u)" -eq 0 ]; then
	
		useradd -m "$username"

		passwd -e -q "$username"

		echo "Konto uzytkownika $username zostalo utworzone."
	
	else
		echo "Musisz posiadac uprawnienia administratora, aby moc utworzyc nowe konto"
		exit 1
	fi
	
done
